# Name of your application. Used to uniquely configure containers.
service: emojicdn

# Name of the container image.
image: benborgers/emojicdn

# Deploy to these servers.
servers:
  - 5.161.225.249

registry:
  username: benborgers

  # Use a Docker Hub access token.
  password:
    - KAMAL_REGISTRY_PASSWORD

healthcheck:
  path: /random
  port: 3000
